repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.9.2
  hooks:
    - id: isort
      args: [--profile, black]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.21.2
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
   - id: flake8
     additional_dependencies: [flake8-typing-imports==1.7.0]
     args: ['--ignore=E501,E203,E731,W503']
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.0.0
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py37-plus]
    - id: nbqa-isort
      args: ['--profile=black']
    - id: nbqa-flake8
      args: ['--ignore=E501,E203,E302,E402,E731,W503']
