exclude: |
    (?x)^(
        blackjax/_version\.py|
    )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.4.0
  hooks:
    - id: mypy
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.10
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
    - id: gitlint
    - id: gitlint-ci
