contact_links:
  - name: Question/Help/Support
    url: https://github.com/blackjax-devs/blackjax/discussions/new
    about: "If you have a question about how to use Blackjax, please start a discussion."
