name: Check code formatting

on:
    push:
        branches:
            - master
    pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev environment
        run: |
            python -m pip install --upgrade pip
            less requirements-dev.txt | grep -v pytest | xargs -i -t pip install {}

      - name: Check types with mypy
        run: |
          mypy blackjax tests
